USE SALAO

USE MASTER

---- POPULAR SALÃO ----
CREATE PROCEDURE SP_POPULAR_SALAO (@NOME VARCHAR(45), @CNPJ VARCHAR(15), @RUA VARCHAR(45), @CIDADE VARCHAR(45), @UF VARCHAR(2), @NUMERO VARCHAR(10) OUTPUT)
AS
BEGIN
	INSERT INTO TB_SALAO
	VALUES(@NOME, @CNPJ, @RUA, @CIDADE, @UF, @NUMERO)
END


---- POPULAR AGENDAMENTO ----
CREATE PROCEDURE SP_POPULAR_AGENDAMENTO (@HORARIO DATETIME, @STATUS VARCHAR(11), @VALTOTAL FLOAT, @ID_SALAO INT, @ID_CLIENTE INT OUTPUT)
AS
BEGIN
	
	INSERT INTO TB_Agendamento
	VALUES(@HORARIO, @STATUS, @VALTOTAL, @ID_SALAO, @ID_CLIENTE)
END


---- POPULAR CLIENTE ----
CREATE PROCEDURE SP_POPULAR_CLIENTE (@NOME VARCHAR(45), @CPF VARCHAR(45), @EMAIL VARCHAR(50), @DT_NASCIMENTO DATETIME, @TELEFONE VARCHAR(45), @SEXO VARCHAR(15), @RUA VARCHAR(45), @CIDADE VARCHAR(45), @NUMERO VARCHAR(45) OUTPUT)
AS
BEGIN
	INSERT INTO TB_Cliente
	VALUES(@NOME, @CPF, @EMAIL, @DT_NASCIMENTO, @TELEFONE, @SEXO, @RUA, @CIDADE, @NUMERO)
END


---- POPULAR FUNCIONARIO ----
CREATE PROCEDURE SP_POPULAR_FUNCIONARIO (@NOME VARCHAR(45), @CPF VARCHAR(45), @TELEFONE VARCHAR(20), @EMAIL VARCHAR(50), @DT_NASCIMENTO DATETIME, @SALARIO FLOAT, @CONTRATO DATETIME, @RUA VARCHAR(45), @CIDADE VARCHAR(45), @BAIRRO VARCHAR(45), @ID_SALAO INT OUTPUT)
AS
BEGIN
	INSERT INTO TB_FUNCIONARIO
	VALUES(@NOME, @CPF, @TELEFONE, @EMAIL, @DT_NASCIMENTO, @SALARIO, @CONTRATO, NULL, @CIDADE, @RUA, @BAIRRO, @ID_SALAO)
END


---- POPULAR SERVICO ----
CREATE PROCEDURE SP_POPULAR_SERVICO (@ID_TIPOSERVICO INT, @ID_FUNCIONARIO INT, @ID_AGENDAMENTO INT, @DESCRICAO VARCHAR(200) OUTPUT)
AS
BEGIN
	INSERT INTO TB_SERVICO
	VALUES(@DESCRICAO, @ID_FUNCIONARIO, @ID_AGENDAMENTO, @ID_TIPOSERVICO)
END


---- POPULAR SERVICO_PRODUTO ----
CREATE PROCEDURE SP_POPULAR_SERVICO_PRODUTO (@CODIGO_PRODUTO INT, @ID_SERVICO INT OUTPUT)
AS
BEGIN
	INSERT INTO TB_PRODUTO_SERVICO
	VALUES (@CODIGO_PRODUTO, @ID_SERVICO)
END


---- POPULAR TIPO_SERVICO ----
CREATE PROCEDURE SP_POPULAR_TIPO_SERVICO(@SERVICO VARCHAR(45), @VALOR FLOAT OUTPUT)
AS
BEGIN
	INSERT INTO TB_TIPO_SERVICO
	VALUES (@SERVICO, @VALOR)
END


---- POPULAR PRODUTO ----
CREATE PROCEDURE SP_POPULAR_PRODUTO (@NOME VARCHAR(45), @QUANTIDADE INT, @VALOR FLOAT OUTPUT)
AS
BEGIN
	INSERT INTO TB_PRODUTO
	VALUES (@NOME, @QUANTIDADE, @VALOR)
END


---- POPULAR ESPECIALIZACAO ----
CREATE PROCEDURE SP_POPULAR_ESPECIALIZACAO (@NOME VARCHAR(45) OUTPUT)
AS
BEGIN
	INSERT INTO TB_ESPECIALIZACAO
	VALUES (@NOME)
END

---- POPULAR FUNCIONARIO_ESPECIALIZACAO ----
CREATE PROCEDURE SP_POPULAR_FUNCIONARIO_ESPECIALIZACAO (@ID INT, @MATRICULA INT OUTPUT)
AS
BEGIN
	INSERT INTO TB_FUNCIONARIO_ESPECIALIZACAO
	VALUES (@MATRICULA, @ID)
END


--------- POPULANDO BANCO ----------

EXEC SP_POPULAR_SALAO @NOME='Cabeleileila Leia Produções', 
					  @CNPJ='01.642.133/0001-24', 
					  @RUA='Rua Afonso Padilha', 
					  @CIDADE='Itaquaquecetuba', 
					  @UF='SP', 
					  @NUMERO='195'

EXEC SP_POPULAR_SALAO @NOME='Cabeleileila Leia Filial', 
					  @CNPJ='75.455.579/0001-86', 
					  @RUA='Rua Afonso Padilha', 
					  @CIDADE='Campo do Brito', 
					  @UF='SE', 
					  @NUMERO='412'

SELECT * FROM TB_SALAO



EXEC SP_POPULAR_CLIENTE @NOME='Ano Cláudio', 
						@CPF='927.182.830-50', 
						@EMAIL='anoclaudio@gmail.com', 
						@DT_NASCIMENTO='2001-11-14', 
						@TELEFONE='7999999999', 
						@SEXO='Feminino', 
						@RUA='Castelo de Andrâde', 
						@CIDADE='Itaquaquecetuba', 
						@NUMERO=NULL
						
EXEC SP_POPULAR_CLIENTE @NOME='Maria Bonita', 
						@CPF='328.348.050-83', 
						@EMAIL='bonitamaria@hotmail.com', 
						@DT_NASCIMENTO='1999-11-03', 
						@TELEFONE='7999999999', 
						@SEXO='Feminino', 
						@RUA='Aquela Rua ali', 
						@CIDADE='Itabaiana', 
						@NUMERO=NULL

SELECT * FROM TB_CLIENTE



EXEC SP_POPULAR_AGENDAMENTO @HORARIO='2024-01-10 18:00',
							@STATUS='AGENDADO',
							@VALTOTAL='250.00', 
							@ID_SALAO=1, 
							@ID_CLIENTE=1

EXEC SP_POPULAR_AGENDAMENTO @HORARIO='2024-01-05 10:00',
							@STATUS='TERMINADO',
							@VALTOTAL=500.00, 
							@ID_SALAO=2, 
							@ID_CLIENTE=2

SELECT * FROM TB_Agendamento



EXEC SP_POPULAR_ESPECIALIZACAO @NOME='Cabeleireiro/a'
EXEC SP_POPULAR_ESPECIALIZACAO @NOME='Esteticista'
EXEC SP_POPULAR_ESPECIALIZACAO @NOME='Manicure e Pedicure'
EXEC SP_POPULAR_ESPECIALIZACAO @NOME='Maquiadora'

SELECT * FROM TB_ESPECIALIZACAO



EXEC SP_POPULAR_FUNCIONARIO @NOME='Beatrice', 
							@CPF='420.837.610-49',
							@TELEFONE='799999999', 
							@EMAIL='lampadailuminada@gmail.com', 
							@DT_NASCIMENTO='2000-02-08',
							@SALARIO= 3000.00, 
							@CONTRATO='2023-03-12', 
							@RUA='Cantinho de Deux', 
							@CIDADE='Cabo Branco', 
							@BAIRRO='Marillio Mello',
							@ID_SALAO=1
							
EXEC SP_POPULAR_FUNCIONARIO @NOME='Erin', 
							@CPF='746.029.030-02',
							@TELEFONE='799999999', 
							@EMAIL='explosion192@gmail.com', 
							@DT_NASCIMENTO='1992-07-28',
							@SALARIO= 2000.00, 
							@CONTRATO='2023-04-16', 
							@RUA='Santa Menefreda', 
							@CIDADE='Pequena Carpa', 
							@BAIRRO='Antonio Azedo', 
							@ID_SALAO=2

SELECT * FROM TB_FUNCIONARIO



EXEC SP_POPULAR_FUNCIONARIO_ESPECIALIZACAO @MATRICULA = 1,
										   @ID = 1
										   
EXEC SP_POPULAR_FUNCIONARIO_ESPECIALIZACAO @MATRICULA = 2,
										   @ID = 4
										   
EXEC SP_POPULAR_FUNCIONARIO_ESPECIALIZACAO @MATRICULA = 1,
										   @ID = 4

SELECT * FROM TB_FUNCIONARIO_ESPECIALIZACAO


EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Hidratação Profunda',
							 @VALOR=120.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Hidratação Normal',
							 @VALOR=80.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Lavagem',
							 @VALOR=70.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Cauterização',
							 @VALOR=150.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Progressiva sem Formol',
							 @VALOR=250.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Progressiva com Formol',
							 @VALOR=350.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Reconstrução',
							 @VALOR=130.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Matização',
							 @VALOR=100.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='SPA Mãos e Pés',
							 @VALOR=150.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Manicure e Pedicure',
							 @VALOR=130.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Maquiagem Completa',
							 @VALOR=270.00
EXEC SP_POPULAR_TIPO_SERVICO @SERVICO='Massagem Completa',
							 @VALOR=200.00

SELECT * FROM TB_TIPO_SERVICO



EXEC SP_POPULAR_PRODUTO @NOME='LOréal Professionnel', 
						@QUANTIDADE='10', 
						@VALOR=134.00 
EXEC SP_POPULAR_PRODUTO @NOME='Borabella', 
						@QUANTIDADE='8', 
						@VALOR=116.98
EXEC SP_POPULAR_PRODUTO @NOME='SP System Professional', 
						@QUANTIDADE='14', 
						@VALOR=240.37
EXEC SP_POPULAR_PRODUTO @NOME='Hidramais', 
						@QUANTIDADE='10', 
						@VALOR=30.99
EXEC SP_POPULAR_PRODUTO @NOME='Sophie Sensual Feelings', 
						@QUANTIDADE='12', 
						@VALOR=48.68

SELECT * FROM TB_PRODUTO



EXEC SP_POPULAR_SERVICO @ID_FUNCIONARIO=1,
						@ID_AGENDAMENTO=1, 
						@ID_TIPOSERVICO=1,
						@DESCRICAO='Lavagem e Hidratação normal de cabelo'

EXEC SP_POPULAR_SERVICO @ID_FUNCIONARIO=2,
						@ID_AGENDAMENTO=1, 
						@ID_TIPOSERVICO=7,
						@DESCRICAO='Lavagem e Hidratação normal de cabelo'

EXEC SP_POPULAR_SERVICO @ID_FUNCIONARIO=2,
						@ID_AGENDAMENTO=2, 
						@ID_TIPOSERVICO=10,
						@DESCRICAO='Manicure e Pedicure'

SELECT * FROM TB_SERVICO



EXEC SP_POPULAR_SERVICO_PRODUTO @CODIGO_PRODUTO=1, 
								@ID_SERVICO=1
								
EXEC SP_POPULAR_SERVICO_PRODUTO @CODIGO_PRODUTO=4, 
								@ID_SERVICO=2

SELECT * FROM TB_PRODUTO_SERVICO



SELECT C.nome as 'Cliente', F.NOME as 'Funcionario', S.descricao as 'Descrição', A.horario, K.NOME
FROM TB_Agendamento A INNER JOIN TB_Cliente C
ON(A.idCliente = C.id)
INNER JOIN TB_Servico S
ON(A.ID = S.idAgendamento)
INNER JOIN TB_FUNCIONARIO F
ON(F.MATRICULA = S.idFuncionario)
INNER JOIN TB_FUNCIONARIO_ESPECIALIZACAO E
ON(E.MATRICULA_FUNCIONARIO = F.MATRICULA)
JOIN TB_ESPECIALIZACAO K
ON(K.ID = E.ID_ESPECIALIZACAO)