USE SALAO

-------- CARGA DIM_TEMPO --------
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO (@DT_INICIAL DATE, @DT_FINAL DATE)
AS
BEGIN
	SET LANGUAGE Brazilian
	
	DECLARE @INICIO DATE, @SEMESTRE VARCHAR(25), @SEMESTRE_INT INT, @TRIMESTRE VARCHAR(25), @FIM_SEMANA VARCHAR(3)

	DELETE FROM DIM_TEMPO
	WHERE (DATA >= @DT_INICIAL AND DATA <= @DT_FINAL) OR 
	      (MES >= DATEPART(mm, @DT_INICIAL) AND MES <= DATEPART(mm, @DT_FINAL)) OR
		  (ANO >= DATEPART(yy, @DT_INICIAL) AND ANO <= DATEPART(yy, @DT_FINAL))

	SET @INICIO = @DT_INICIAL

	WHILE(@DT_INICIAL <= @DT_FINAL)
	BEGIN

		-- Calculo de Semestre
		IF (MONTH(@DT_INICIAL) <= 6)
		BEGIN
			SET @SEMESTRE = CONCAT('1º Semestre / ', YEAR(@DT_INICIAL))
			SET @SEMESTRE_INT = 1
		END
		ELSE
		BEGIN
			SET @SEMESTRE = CONCAT('2º Semestre / ', YEAR(@DT_INICIAL))
			SET @SEMESTRE_INT = 2
		END

		-- Trimestre
		SET @TRIMESTRE = CONCAT(DATENAME(qq, @DT_INICIAL), '° Trimestre / ', YEAR(@DT_INICIAL))

		-- Calculo Final de Semana
		IF (DATENAME(dw, @DT_INICIAL) = 'Sábado' or DATENAME(dw, @DT_INICIAL) = 'Domingo')
		BEGIN
			SET @FIM_SEMANA = 'SIM'
		END
		ELSE
		BEGIN
			SET @FIM_SEMANA = 'NAO'
		END

		-- Inserção do Dia
		INSERT INTO DIM_TEMPO(NIVEL, DATA, DIA, DIA_SEMANA, FIM_SEMANA, FERIADO, FL_FERIADO, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
		VALUES ('DIA', @DT_INICIAL, DATEPART(dd, @DT_INICIAL), DATENAME(dw, @DT_INICIAL), @FIM_SEMANA, NULL, 'NAO', DATEPART(mm, @DT_INICIAL), DATENAME(mm, @DT_INICIAL), DATENAME(qq, @DT_INICIAL), @TRIMESTRE, @SEMESTRE_INT, @SEMESTRE, YEAR(@DT_INICIAL)) 
		
		SET @DT_INICIAL = DATEADD(dd, 1, @DT_INICIAL)
	END

	--Inserção do Mês
	INSERT INTO DIM_TEMPO (NIVEL, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
	SELECT DISTINCT 'MES', MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO
			FROM DIM_TEMPO
			WHERE DATA >= @INICIO AND DATA <= @DT_FINAL

	--Inserção do Ano
	INSERT INTO DIM_TEMPO (NIVEL, ANO)
	SELECT DISTINCT 'ANO', ANO
			FROM DIM_TEMPO
			WHERE DATA >= @INICIO AND DATA <= @DT_FINAL
END