USE SALAO

-- Qual cidade teve mais agendamentos por trimestre
SELECT S.CIDADE, T.NOME_TRIMESTRE, SUM(A.NUMERO_AGENDAMENTO) AS TOTAL_AGENDAMENTOS
FROM FATO_AGENDAMENTO A JOIN DIM_SALAO S 
ON A.ID_SALAO = S.ID_SALAO JOIN DIM_TEMPO T 
ON A.ID_DT_AGENDAMENTO = T.ID_TEMPO
GROUP BY S.CIDADE, T.NOME_TRIMESTRE
ORDER BY TOTAL_AGENDAMENTOS DESC

-- Quais salões com menos agendamentos por trimestre
SELECT S.NM_SALAO, T.NOME_TRIMESTRE AS SALAO, SUM(A.NUMERO_AGENDAMENTO) AS TOTAL_AGENDAMENTOS
FROM FATO_AGENDAMENTO A JOIN DIM_SALAO S 
ON (A.ID_SALAO = S.ID_SALAO)
JOIN DIM_TEMPO T 
ON (A.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY S.NM_SALAO, T.NOME_TRIMESTRE
ORDER BY TOTAL_AGENDAMENTOS ASC

-- Quais salões com mais agendamentos, por trimestre
SELECT S.NM_SALAO, T.NOME_TRIMESTRE AS SALAO, SUM(A.NUMERO_AGENDAMENTO) AS TOTAL_AGENDAMENTOS
FROM FATO_AGENDAMENTO A JOIN DIM_SALAO S 
ON (A.ID_SALAO = S.ID_SALAO)
JOIN DIM_TEMPO T 
ON (A.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY S.NM_SALAO, T.NOME_TRIMESTRE
ORDER BY TOTAL_AGENDAMENTOS DESC

-- Qual mês ocorrem mais agendamentos
SELECT T.NOME_MES, SUM(A.NUMERO_AGENDAMENTO) AS TOTAL_AGENDAMENTOS
FROM FATO_AGENDAMENTO A JOIN DIM_TEMPO T 
ON (A.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY T.NOME_MES
ORDER BY TOTAL_AGENDAMENTOS DESC

-- Qual mês ocorrem mais cancelamentos de agendamentos
SELECT T.NOME_MES, SUM(A.NUMERO_AGENDAMENTO) AS TOTAL_CANCELAMENTOS
FROM FATO_AGENDAMENTO A JOIN DIM_TEMPO T 
ON (A.ID_DT_AGENDAMENTO = T.ID_TEMPO)
JOIN DIM_STATUS S 
ON (A.ID_STATUS = S.ID_STATUS)
WHERE S.STATUS = 'CANCELADO'
GROUP BY T.NOME_MES
ORDER BY TOTAL_CANCELAMENTOS DESC

-- Qual a faixa etária que mais frequenta os salões por cidade por mês
SELECT A.CIDADE, T.MES, F.FAIXA_ETARIA, SUM(S.NUMERO_SERVICO) SERVICOS_ATENDIDOS
FROM FATO_SERVICO S JOIN DIM_FAIXA_ETARIA F
ON(S.ID_FAIXA_ETARIA = F.ID_FAIXA_ETARIA)
JOIN DIM_SALAO A
ON(S.ID_SALAO = A.ID_SALAO)
JOIN DIM_TEMPO T
ON(S.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY F.FAIXA_ETARIA, A.CIDADE, T.MES
ORDER BY SERVICOS_ATENDIDOS DESC

-- Qual serviço mais pedido, por salão, por período
SELECT A.NM_SALAO, T.NOME_TRIMESTRE, SUM(S.NUMERO_SERVICO) SERVICOS_ATENDIDOS
FROM FATO_SERVICO S JOIN DIM_TEMPO T
ON(S.ID_DT_AGENDAMENTO = T.ID_TEMPO)
JOIN DIM_SALAO A
ON(S.ID_SALAO = A.ID_SALAO)
GROUP BY A.NM_SALAO, T.NOME_TRIMESTRE
ORDER BY SERVICOS_ATENDIDOS DESC

-- Quais funcionários que mais atendem serviços, por salão por mês
SELECT T.MES, F.NM_FUNCIONARIO, SUM(S.NUMERO_SERVICO) SERVICOS_ATENDIDOS
FROM FATO_SERVICO S JOIN DIM_FUNCIONARIO F
ON(S.ID_FUNCIONARIO = F.ID_FUNCIONARIO)
JOIN DIM_TEMPO T
ON(S.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY  NM_FUNCIONARIO, T.MES
ORDER BY SERVICOS_ATENDIDOS DESC

-- Quais salões agendam menos serviços, por cidade por período
SELECT A.CIDADE, T.NOME_TRIMESTRE, A.NM_SALAO, SUM(S.NUMERO_SERVICO) SERVICOS_ATENDIDOS
FROM FATO_SERVICO S JOIN DIM_SALAO A
ON(S.ID_SALAO = A.ID_SALAO)
JOIN DIM_TEMPO T
ON(S.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY A.CIDADE, T.NOME_TRIMESTRE
ORDER BY SERVICOS_ATENDIDOS ASC

-- Qual a média de renda por salão por semestre
SELECT T.NOME_SEMESTRE, A.NM_SALAO, AVG(S.VALOR_SERVICO) VALOR_SERVICO
FROM FATO_SERVICO S JOIN DIM_SALAO A
ON(S.ID_SALAO = A.ID_SALAO)
JOIN DIM_TEMPO T
ON(S.ID_DT_AGENDAMENTO = T.ID_TEMPO)
GROUP BY A.NM_SALAO, T.NOME_SEMESTRE